DROP TABLE Restaurant;

CREATE TABLE Restaurant (
	res_id	NUMBER		NOT NULL,
	RES_NAME	VARCHAR2(300)		NULL,
	gugunnm	VARCHAR2(100)		NULL,
	lng	VARCHAR2(20)		NULL,
	lat	VARCHAR2(20)		NULL,
	place	VARCHAR2(300)		NULL,
	addr	VARCHAR2(200)		NULL,
	tel	VARCHAR2(200)		NULL,
	homepage	CLOB		NULL,
	time	VARCHAR2(500)		NULL,
	img	CLOB		NULL,
	img_thumb	CLOB		NULL,
	detail	CLOB		NULL,
	price	NUMBER		NULL,
	READCOUNT	NUMBER		NULL,
	registration DATE		NULL
);

DROP TABLE USER;

CREATE TABLE Member (
	User_CODE	NUMBER		NOT NULL,
	user_id	varchar2(100)		NOT NULL,
	user_pw	varchar2(100)		NULL,
	user_name	varchar2(100)		NULL,
	user_phone	varchar2(100)		NULL,
	user_email	varchar2(100)		NULL,
	USER_STAUS	VARCHAR2(1)	DEFAULT 'Y'	NULL
);

DROP TABLE Kind;

CREATE TABLE Kind (
	kind_id	NUMBER		NOT NULL,
	kind_name	VARCHAR2(500)		NULL,
	ceoname	VARCHAR2(500)		NULL,
	adress	VARCHAR2(500)		NULL,
	tel	VARCHAR2(500)		NULL,
	cncode	VARCHAR2(500)		NULL,
	cn	VARCHAR2(500)		NULL,
    localea	VARCHAR2(500)		NULL,
	localecode	VARCHAR2(500)		NULL,
	kind_content	CLOB		NULL,
	parking	VARCHAR2(1)		NULL,
	bsntime	VARCHAR2(100)		NULL,
	img1	VARCHAR2(500)		NULL,
	img2	VARCHAR2(500)		NULL,
	cnt	NUMBER		NULL
);

DROP TABLE BookMark;

CREATE TABLE BookMark (
	BM_CODE	NUMBER		NOT NULL,
	BMC_CODE	NUMBER		NOT NULL,
	User_CODE	NUMBER		NOT NULL,
	CODE	NUMBER		NULL
);

DROP TABLE ACReservation;

CREATE TABLE ACReservation (
	AR_CODE	NUMBER		NOT NULL,
	User_CODE	NUMBER		NOT NULL,
	AC_CODE	NUMBER		NOT NULL,
	AR_IN	VARCHAR2(100)		NULL,
	AR_OUT	VARCHAR2(100)		NULL,
	AR_RTIME	DATE		NULL,
	AR_PEOPLE	NUMBER		NULL
);

DROP TABLE Room;

CREATE TABLE Room (
	code	NUMBER		NOT NULL,
	name	VARCHAR2(500)		NULL,
	adress	VARCHAR2(500)		NULL,
	readcount	NUMBER		NULL,
	localcode	VARCHAR2(500)		NULL,
	tel	VARCHAR2(500)		NULL,
	image	VARCHAR2(500)		NULL,
	image2	VARCHAR2(500)		NULL,
	mapx	VARCHAR2(500)		NULL,
	mapy	VARCHAR2(500)		NULL,
	price	NUMBER		NULL
);

DROP TABLE BookMarkCategory;

CREATE TABLE BookMarkCategory (
	BMC_CODE	NUMBER		NOT NULL,
	BMC_NAME	VARCHAR2(10)		NULL
);

DROP TABLE Destination;

CREATE TABLE Destination (
	de_id	NUMBER		NOT NULL,
	name	VARCHAR2(300)		NULL,
	gugunnm	VARCHAR2(100)		NULL,
	lat	VARCHAR2(100)		NULL,
	lng	VARCHAR2(100)		NULL,
    place	VARCHAR2(300)		NULL,
	title	VARCHAR2(300)		NULL,
	subtitle	VARCHAR2(300)		NULL,
	addr	VARCHAR2(210)		NULL,
	tel	VARCHAR2(200)		NULL,
	homepage	VARCHAR2(200)		NULL,
	trfcinfo	VARCHAR2(580)		NULL,
	usageday	VARCHAR2(500)		NULL,
	hldyinfo	VARCHAR2(500)		NULL,
	usage_day_week	VARCHAR2(500)		NULL,
	amount	VARCHAR2(500)		NULL,
	middle_size_rm	CLOB		NULL,
	img	CLOB		NULL,
	thumb	CLOB		NULL,
	detail	CLOB		NULL
);

ALTER TABLE Destination ADD CONSTRAINT PK_DESTINATION PRIMARY KEY (
	de_id
);

DROP TABLE Festival;

CREATE TABLE Festival (
	fe_id	NUMBER		NOT NULL,
	fe_title	VARCHAR2(300)		NULL,
	gugunnm	VARCHAR2(100)		NULL,
	LAT	VARCHAR2(20)		NULL,
	LNG	VARCHAR2(20)		NULL,
	PLACE	VARCHAR2(300)		NULL,
	TITLE	VARCHAR2(300)		NULL,
	SUBTITLE	VARCHAR2(300)		NULL,
	MAIN_PLACE	VARCHAR2(100)		NULL,
	ADDR1	VARCHAR2(200)		NULL,
	ADDR2	VARCHAR2(200)		NULL,
	tel	VARCHAR2(200)		NULL,
	homepage	VARCHAR2(200)		NULL,
	trfcinfo	VARCHAR2(500)		NULL,
	time	VARCHAR2(500)		NULL,
	amount	VARCHAR2(500)		NULL,
	img	VARCHAR2(500)		NULL,
	img_thumb	VARCHAR2(500)		NULL,
	detail	CLOB		NULL,
	middle_size_rm1	VARCHAR2(500)		NULL,
	READCOUNT	NUMBER		NULL,
	registration	DATE		NULL
);

DROP TABLE BoardCategory;

CREATE TABLE BoardCategory (
	B_Ccode	NUMBER		NOT NULL,
	B_CNAME	VARCHAR2(200)		NULL
);

DROP TABLE Board;

CREATE TABLE Board (
	B_CODE	NUMBER		NOT NULL,
	User_CODE	NUMBER		NOT NULL,
	B_Ccode	NUMBER		NOT NULL,
	Title	VARCHAR2(500)		NULL,
	Content	CLOB		NULL,
	BDATE	DATE		NULL,
	READCOUNT	NUMBER		NULL,
	STATUS	VARCHAR2(1)	DEFAULT 'Y'NULL
);

DROP TABLE GPReservation;

CREATE TABLE GPReservation (
	GP_CODE	NUMBER		NOT NULL,
	User_CODE	NUMBER		NOT NULL,
	Key	NUMBER		NOT NULL,
	GR_TIME	VARCHAR2(100)		NULL,
	GR_RTIME	DATE		NULL,
	PEOPLE_NUM	NUMBER		NULL
);

DROP TABLE COMMENT;

CREATE TABLE "COMMENT"(
	C_CODE	NUMBER		NOT NULL,
	B_CODE	NUMBER		NOT NULL,
	User_CODE	NUMBER		NOT NULL,
	C_CONTENT	CLOB		NULL,
	C_DATE	DATE		NULL
);

ALTER TABLE Restaurant ADD CONSTRAINT PK_RESTAURANT PRIMARY KEY (
	res_id
);

ALTER TABLE USER ADD CONSTRAINT PK_USER PRIMARY KEY (
	User_CODE
);

ALTER TABLE Kind ADD CONSTRAINT PK_KIND PRIMARY KEY (
	kind_id
);

ALTER TABLE BookMark ADD CONSTRAINT PK_BOOKMARK PRIMARY KEY (
	BM_CODE
);

ALTER TABLE ACReservation ADD CONSTRAINT PK_ACRESERVATION PRIMARY KEY (
	AR_CODE
);

ALTER TABLE Room ADD CONSTRAINT PK_ROOM PRIMARY KEY (
	code
);

ALTER TABLE BookMarkCategory ADD CONSTRAINT PK_BOOKMARKCATEGORY PRIMARY KEY (
	BMC_CODE
);

ALTER TABLE Destination ADD CONSTRAINT PK_DESTINATION PRIMARY KEY (
	TD_CODE
);

ALTER TABLE Festival ADD CONSTRAINT PK_FESTIVAL PRIMARY KEY (
	fe_id
);

ALTER TABLE BoardCategory ADD CONSTRAINT PK_BOARDCATEGORY PRIMARY KEY (
	B_Ccode
);

ALTER TABLE Board ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	B_CODE
);

ALTER TABLE GPReservation ADD CONSTRAINT PK_GPRESERVATION PRIMARY KEY (
	GP_CODE
);

ALTER TABLE COMMENT ADD CONSTRAINT PK_COMMENT PRIMARY KEY (
	C_CODE
);
--===========================================================================
SELECT
    * FROM destination;
desc destination;

SELECT
    * FROM festival;
desc festival;

SELECT
    * FROM kind;
desc kind;

SELECT
    * FROM restaurant;
desc restaurant;

SELECT
    * FROM room;
desc room;

